name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' 
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --name=VideoDL --onefile --windowed --add-data "resources;resources" --icon=resources/icons/icon.ico main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoDL-Windows
        path: dist/VideoDL.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/VideoDL.exe
        draft: false
        generate_release_notes: true